#!/bin/bash

argnum=$#

if [ "$argnum" -lt 3 ]
then
  echo "Usgae:"
  echo "    $ combineJars jar1 jar2 newjar"
  echo
else
  jar1=$1
  jar2=$2
  newjar=$3

  mkdir -p tmpJarDir

  cd tmpJarDir; jar -xf ../$jar1; cd ..
  cd tmpJarDir; jar -xf ../$jar2; cd ..
  jar -cvf $newjar -C tmpJarDir .

  rm -rf tmpJarDir
fi
