#!/bin/bash
# http://blog.htbaa.com/news/tmux-scripting

tmux split-window -hp 20
tmux split-window -v

# in pane 0, vi
tmux send-keys -t 0 "vi $1" Enter
# in pane 1, vulture
tmux send-keys -t 1 "vulture $1 comptex" Enter
# in pane 2, evince 
tmux send-keys -t 2 "evince *.pdf &" Enter
