#!/bin/bash

git add .
git commit -m 'yes'
git push

source ~/.bashColors

sizeOfDir=$( echo `du -sh` | cut -d " " -f1 )


sizeOfRepo=$( git count-objects -vH | grep 'size-pack' )
printf "${BLUE}Size of dir (including ignored): ${BLUE}$sizeOfDir\n"
printf "$sizeOfRepo\n"
printf "${ORANGE}$(date)${NC}\n"

