#!/bin/bash

git add .
git commit -m 'yes'
git push

ORANGE='\033[0;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

sizeOfDir=$( echo `du -sh` | cut -d " " -f1 )
printf "${CYAN}size of repo: $sizeOfDir\n"
printf "${ORANGE}$(date)${NC}\n"
