#!/bin/bash

file="$1"
dest="/home/arthur/Repo/luiarthur.github.io/assets/litreview"

if [ $# == 0 ]
then
  echo
  echo "Enter a file to add to litreview. For example: "
  echo "  $ litreview myfile.pdf"
  echo
else
  cp $file $dest
fi

exit 0
