#!/bin/bash

argnum=$#

if [ $argnum == 0 ]
then
  echo
  echo "  This scripts accepts a markdown document name as an argument"
  echo "  and generates a new markdown document template"
  echo
  echo "  Usage:"
  echo "        $ mdgen nameOfNewMarkdownDocument"
  echo
else
  fname="$1"
  # create an initial build.sbt file
  echo "---
title: \"Title\"
author: Arthur Lui
date: \"\\\\today\"
geometry: margin=1in
fontsize: 12pt

# Uncomment if using natbib:

# bibliography: BIB.bib
# bibliographystyle: plain 

# This is how you use bibtex refs: @nameOfRef
# see: http://www.mdlerch.com/tutorial-for-pandoc-citations-markdown-to-latex.html

header-includes: 
#{{{1
    - \\usepackage{bm}
    - \\usepackage{bbm}
    - \\usepackage{graphicx}
    #- \\pagestyle{empty}
    - \\newcommand{\\norm}[1]{\\left\\lVert#1\\right\\rVert}
    - \\newcommand{\\p}[1]{\\left(#1\\right)}
    - \\newcommand{\\bk}[1]{\\left[#1\\right]}
    - \\newcommand{\\bc}[1]{ \\left\\{#1\\right\\} }
    - \\newcommand{\\abs}[1]{ \\left|#1\\right| }
    - \\newcommand{\\mat}{ \\begin{pmatrix} }
    - \\newcommand{\\tam}{ \\end{pmatrix} }
    - \\newcommand{\\suml}{ \\sum_{i=1}^n }
    - \\newcommand{\\prodl}{ \\prod_{i=1}^n }
    - \\newcommand{\\ds}{ \\displaystyle }
    - \\newcommand{\\df}[2]{ \\frac{d#1}{d#2} }
    - \\newcommand{\\ddf}[2]{ \\frac{d^2#1}{d{#2}^2} }
    - \\newcommand{\\pd}[2]{ \\frac{\\partial#1}{\\partial#2} }
    - \\newcommand{\\pdd}[2]{\\frac{\\partial^2#1}{\\partial{#2}^2} }
    - \\newcommand{\\N}{ \\mathcal{N} }
    - \\newcommand{\\E}{ \\text{E} }
    - \\def\\given{~\\bigg|~}
    # Figures in correct place
    - \\usepackage{float}
    - \\def\\beginmyfig{\\begin{figure}[H]\\center}
    - \\def\\endmyfig{\\end{figure}}
    - \\newcommand{\iid}{\\overset{iid}{\\sim}}
    - \\newcommand{\\ind}{\\overset{ind}{\\sim}}
    - \\newcommand{\\I}{\\mathrm{\\mathbf{I}}}
    #
    - \\allowdisplaybreaks
    - \\def\\M{\\mathcal{M}}
#}}}1
---

[comment]: <> (%
  These are comments
%)


[//]: # ( example image embedding
{{{1
\\beginmyfig
\\includegraphics[height=0.5\\textwidth]{path/to/img/img.pdf}
\\caption{some caption}
\\label{fig:mylabel}
% reference by: \\ref{fig:mylabel}
\\endmyfig
)
[//]: # ( example image embedding
> ![some caption.\\label{mylabel}](path/to/img/img.pdf){ height=70% }
)

[//]: # ( example two figs side-by-side
\\begin{figure*}
  \\begin{minipage}{.45\\linewidth}
    \\centering \\includegraphics[height=1\\textwidth]{img1.pdf}
    \\caption{some caption}
    \\label{fig:myLabel1}
  \\end{minipage}\\hfill
  \\begin{minipage}{.45\\linewidth}
    \\centering \\includegraphics[height=1\\textwidth]{img2.pdf}
    \\caption{some caption}
    \\label{fig:myLabel2}
  \\end{minipage}
\\end{figure*}
1}}}
)


[//]: # (Footnotes:)

" > $fname.md

  echo "#!/bin/bash

# -s        =>  create standalone file (in this case report.tex latex file)
# --toc     =>  create table of contents
# --natbib  =>  use the natbib package in latex
# -o        =>  output file name

pandoc $fname.md -s -o $fname.tex

pdflatex $fname.tex
bibtex $fname.aux
pdflatex $fname.tex
pdflatex $fname.tex
rm -f *.{log,aux,nav,out,snm,toc,blg,bbl}
rm -f $fname.tex
" > compile

  chmod +x compile
fi

exit 0
