#!/usr/bin/env python

import sys, os

if len(sys.argv) != 2:
    print "Usage:\n"
    print "$ newH my_new_file.h"
    sys.exit(1)

NEW_FILE_NAME = sys.argv[1]

### Create Contents
NEW_FILE_CONTENTS = """#ifndef <NAME_OF_FILE>
#define <NAME_OF_FILE>

#endif
""".replace("<NAME_OF_FILE>", NEW_FILE_NAME.upper())


with open(NEW_FILE_NAME,"w") as f:
    f.write(NEW_FILE_CONTENTS)

