#!/usr/bin/env python

import sys, os

if len(sys.argv) != 2:
    print "Usage:\n"
    print "$ newH my_new_file.h"
    sys.exit(1)

NEW_FILE_NAME = sys.argv[1]

### Create Contents
def gen_new_hfile_contents(f):
    return """#ifndef <NAME_OF_FILE>
#define <NAME_OF_FILE>

#endif
""".replace("<NAME_OF_FILE>", f.upper()).replace('.', '_')

NEW_FILE_CONTENTS = gen_new_hfile_contents(NEW_FILE_NAME)

if NEW_FILE_NAME in os.listdir("./"):
    overwrite = raw_input(NEW_FILE_NAME + ' already exists. Overwrite? (Y/N):  ')
    if overwrite[0] not in ['Y', 'y']:
        sys.exit(0)

with open(NEW_FILE_NAME,"w") as f:
    f.write(NEW_FILE_CONTENTS)



