#!/bin/bash

#tmux split-window -h -p 70
#tmux send-keys -t 0 "
#clear
#echo; cal -h | grep -C6 --color "$(date +%e)"; gcalbird
#"

tmux new -d -s gcal-session
tmux send-keys -t gcal-session "
tmux split-window -h -p 70
clear
echo; cal -h | grep -C6 --color "$(date +%e)"; gcalbird
"
tmux attach -t gcal-session
