#!/bin/bash

argnum=$#

if [ $argnum == 0 ]
then
  echo
  echo "  This scripts accepts a project name as an argument"
  echo "  and generates a new sbt project."
  echo
  echo "  Usage:"
  echo "        $ sbtGen nameOfNewProject"
  echo
else
  projName="$1"
  mkdir -p src/{main,test}/{java,resources,scala}
  mkdir lib project target

  # create an initial build.sbt file
  echo "name := \"$projName\"

version := \"0.1.0\"

scalaVersion := \"2.11.8\"" > build.sbt

fi

exit 0
