#!/bin/bash


sudo apt-get install tmux
sudo apt-get install vim-gnome
mkdir -p ~/repo
sudo apt-get install git
#git clone https://github.com/luiarthur/myBin ~/repo

### For recompiling C / C++ (especially Rcpp)
sudo apt-get install ccache

### For keyboard mouse keys ###
### see https://askubuntu.com/questions/150290/adjust-mouse-keys-in-12-04
sudo apt-get install xkbset
xkbset ma 60 10 10 5 2

# Copy the following to HOME:
mkdir -p ~/bin
mkdir -p ~/lib/R_lib
mkdir -p ~/.vim/colors
mkdir -p ~/.texmf-config/tex # for custom beamer theme
mkdir -p ~/.R

ln -s $PWD/redmagick.vim ~/.vim/colors
ln -s $PWD/mouse ~/bin/mouse
cp tmux.conf ~/.tmux.conf
cp vimrc ~/.vimrc
cp vimrc.line-feeder-3 ~/.vimrc.line-feeder-3

cp bashrc ~/.bashrc
cp gitconfig ~/.gitconfig
cp gitignore_global ~/.gitignore_global
cp pythonrc ~/.pythonrc
cp Rprofile ~/.Rprofile
cp Renviron ~/.Renviron
cp Makevars ~/.R/
cp resources ~/bin/resources
cp ssh_config ~/.ssh/config

# Soft link the following to ~/bin:
ln -s $PWD/dirsize ~/bin/dirsize
ln -s $PWD/vulture ~/bin/vulture
ln -s $PWD/gush ~/bin/gush
ln -s $PWD/gcal ~/bin/gcal
ln -s $PWD/gcalbird ~/bin/gcalbird
ln -s $PWD/ok ~/bin/ok
ln -s $PWD/editlatex ~/bin/editlatex
ln -s $PWD/md ~/bin/md
ln -s $PWD/minify ~/bin/minify
ln -s $PWD/litreview ~/bin/litreview
ln -s $PWD/comptex ~/bin/comptex
ln -s $PWD/bashColors ~/.bashColors
ln -s $PWD/sbtgen ~/bin/sbtgen
ln -s $PWD/sbt-cleanstage ~/bin/sbt-cleanstage
ln -s $PWD/combineJars ~/bin/combineJars
ln -s $PWD/mdgen ~/bin/mdgen
ln -s $PWD/beamergen ~/bin/beamergen
ln -s $PWD/beamerthemealui.sty ~/.texmf-config/tex/beamerthemealui.sty
ln -s $PWD/asaproc.cls ~/.texmf-config/tex/asaproc.cls
ln -s $PWD/asamdgen ~/bin/asamdgen

# git clones:
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
