#!/bin/bash


#sudo apt-get install tmux
#sudo apt-get install vim-gnome
#mkdir -p ~/Repo
#sudo apt-get install git
#git clone https://github.com/luiarthur/myBin ~/Repo
#git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim


# Copy the following to HOME:
cp tmux.conf ~/.tmux.conf
cp vimrc ~/.vimrc
cp vimrc.line-feeder-3 ~/.vimrc.line-feeder-3

cp bashrc ~/.bashrc
cp gitconfig ~/.gitconfig
cp gitignore_global ~/.gitignore_global
cp pythonrc ~/.pythonrc
cp Rprofile ~/.Rprofile

# Soft link the following to ~/bin:
mkdir -p ~/bin
ln -s $PWD/dirsize ~/bin/dirsize
ln -s $PWD/resources ~/bin/resources
ln -s $PWD/vulture ~/bin/vulture
ln -s $PWD/gush ~/bin/gush
ln -s $PWD/gcal ~/bin/gcal
ln -s $PWD/gcalbird ~/bin/gcalbird
ln -s $PWD/ok ~/bin/ok
ln -s $PWD/editlatex ~/bin/editlatex
ln -s $PWD/md ~/bin/md
ln -s $PWD/minify ~/bin/minify
ln -s $PWD/litreview ~/bin/litreview
ln -s $PWD/comptex ~/bin/comptex

# For use in UCSC
ln -s $PWD/arrow ~/bin/arrow
ln -s $PWD/printers ~/bin/printers
