#!/bin/bash

# See: https://askubuntu.com/questions/19764/how-does-one-set-up-a-midi-keyboard

qjackctl &
zynaddsubfx &

# in JackConnect, make sure to 
# 1. Connect -> ALSA -> Casio (out) to Zyn (in)
# 2. Connect -> Audio -> zyn(out) to system (in)
# 
# Note that musescore works similarly. 
# Q: Can I use midiculous?
