#!/bin/bash

# See: https://askubuntu.com/questions/19764/how-does-one-set-up-a-midi-keyboard

qjackctl &
zynaddsubfx &
vmpk &

# in JackConnect, make sure to 
# 1. Connect -> ALSA -> Casio (out) to Zyn (in)
# 2. Connect -> Audio -> zyn(out) to system (in)
# 
# Note that musescore works similarly. 
# Q: Can I use midiculous?
#
# Check out: https://www.youtube.com/watch?v=Y-BV2B5eFHw
# 
# If this script doesn't work the first time, run it again.
#
# To use sound again afterwards, run `reset_audio`, or simply:
# ```bash
# pulseaudio -k && sudo alsa force-reload
# ```
#
