#!/bin/bash

# Make a programs dir
mkdir -p ~/programs
mkdir -p ~/.ssh

# Install brew
git clone https://github.com.mxcl/homebrew.git ~/programs

# Create directories
mkdir -p ~/bin
mkdir -p ~/lib/R_lib
mkdir -p ~/.vim/colors
mkdir -p ~/.texmf-config/tex # for custom beamer theme
mkdir -p ~/.R

# Install Vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# Install gnu-sed
brew install gnu-sed # For gush

# Copy scripts
cp profile ~/.profile
cp vimrc ~/.vimrc
cp ../vimrc.line-feeder-3 ~/.vimrc.line-feeder-3
cp ../tmux.conf ~/.tmux.conf
cp ../gitconfig ~/.gitconfig
cp ../gitignore_global ~/.gitignore_global
cp ../pythonrc ~/.pythonrc
cp ../Rprofile ~/.Rprofile
cp ../Renviron ~/.Renviron
cp ../Makevars ~/.R/
cp ../resources ~/bin/resources
cp ../ssh_config ~/.ssh/config

# Link scripts
ln -s $PWD/../redmagick.vim ~/.vim/colors/redmagick.vim
ln -s $PWD/../vulture ~/bin/vulture
ln -s $PWD/../dirsize ~/bin/dirsize
ln -s $PWD/../gush ~/bin/gush
ln -s $PWD/../md ~/bin/md
ln -s $PWD/../minify ~/bin/minify
ln -s $PWD/../litreview ~/bin/litreview
ln -s $PWD/../comptex ~/bin/comptex
ln -s $PWD/../bashColors ~/.bashColors
ln -s $PWD/../sbtgen ~/bin/sbtgen
ln -s $PWD/../sbt-cleanstage ~/bin/sbt-cleanstage
ln -s $PWD/../combineJars ~/bin/combineJars
ln -s $PWD/../mdgen ~/bin/mdgen
ln -s $PWD/../beamergen ~/bin/beamergen
ln -s $PWD/../beamerthemealui.sty ~/.texmf-config/tex/beamerthemealui.sty
ln -s $PWD/../asaproc.cls ~/.texmf-config/tex/asaproc.cls
ln -s $PWD/../asamdgen ~/bin/asamdgen


# Install software
brew install tmux
brew install MacVim
brew install wget

# Installing python / pip / Setuptools (default osx python doesn't have pip)
brew install python

# Install MaxTex
# http://tex.stackexchange.com/questions/106113/is-there-any-way-to-have-a-latex-compiler-on-a-mac-without-root-access
#brew install caskroom/cask/brew-cask
#brew cask install MacTex
#brew cask install texmaker



