#!/bin/bash

# Make a programs dir
mkdir -p ~/programs
mkdir -p ~/.ssh

# Install brew
git clone https://github.com.mxcl/homebrew.git ~/programs

# Create directories
mkdir -p ~/bin
mkdir -p ~/lib/R_lib
mkdir -p ~/.vim/colors
mkdir -p ~/.R
mkdir -p ~/Library/texmf/tex # for custom beamer theme
mkdir -p ~/.vim/spell

# Install Vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# Install gnu-sed for gush
# If gnu-sed is previously installed,
# brew uninstall gnu-sed
brew install gnu-sed --with-default-names

# Copy scripts
cp profile ~/.profile
cp tmux.conf ~/.tmux.conf
cp vimrc ~/.vimrc
cp ../vimrc.line-feeder-3 ~/.vimrc.line-feeder-3
cp ../gitconfig ~/.gitconfig
cp ../gitignore_global ~/.gitignore_global
cp ../pythonrc ~/.pythonrc
touch ~/.pythonhistory
cp ../Rprofile ~/.Rprofile
cp ../Renviron ~/.Renviron
cp ../resources ~/bin/resources
cp ../ssh_config ~/.ssh/config

# Link scripts
ln -s $PWD/../redmagick.vim ~/.vim/colors/redmagick.vim
ln -s $PWD/../vulture ~/bin/vulture
ln -s $PWD/../dirsize ~/bin/dirsize
ln -s $PWD/../gush ~/bin/gush
ln -s $PWD/../md ~/bin/md
ln -s $PWD/../minify ~/bin/minify
ln -s $PWD/../litreview ~/bin/litreview
ln -s $PWD/../comptex ~/bin/comptex
ln -s $PWD/../bashColors ~/.bashColors
ln -s $PWD/../sbtgen ~/bin/sbtgen
ln -s $PWD/../sbt-cleanstage ~/bin/sbt-cleanstage
ln -s $PWD/../combineJars ~/bin/combineJars
ln -s $PWD/../mdgen ~/bin/mdgen
ln -s $PWD/../beamergen ~/bin/beamergen
ln -s $PWD/../beamerthemealui.sty ~/Library/texmf/tex/beamerthemealui.sty
ln -s $PWD/../asaproc.cls ~/Library/texmf/tex/asaproc.cls
ln -s $PWD/../asamdgen ~/bin/asamdgen


# Install software
# Install TMUX
brew install tmux # Note in osx, to change pane size: Ctrl-b (release) + Option + Arrow
brew install reattach-to-user-namespace # so that open can be used in tmux
#brew upgrade reattach-to-user-namespace

brew install MacVim
brew install sbt
brew install scala
brew install python # Installs python / pip / Setuptools (default osx python doesn't have pip)
brew install wget # 15 minutes. Consider just doing `curl -O someurl.com`
brew install pandoc # SLOW!...

# Install R
brew tap homebrew/science
brew install r # SLOW

# Install MaxTex
# http://tex.stackexchange.com/questions/106113/is-there-any-way-to-have-a-latex-compiler-on-a-mac-without-root-access
#brew install caskroom/cask/brew-cask
#brew cask install MacTex
#brew cask install texmaker

# At LLNL, behind firewall, need to add repo manually.
# See https://stackoverflow.com/questions/18505176/unresolved-dependency-sbt-0-13-0-after-update
# In file ~/.sbt/repositories, put this:
#[repositories]
#  local
#  sbt-releases-repo: http://repo.typesafe.com/typesafe/ivy-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
#  sbt-plugins-repo: http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
#  maven-central: http://repo1.maven.org/maven2/
